### PR TITLE
Re-enable direct gets and update nats-server and nats.go versions

### PR DESCRIPTION
**Pull request by bruth**

### CODE REVIEW

**Comment by bruth** [comment]
@brandond I check out the Drone CI and noticed that for the NATS 2.10.11, the API server was failing to come up, but its not clear why: 
image
NATS 2.9.25 and NATS embedded both worked.

**Comment by brandond** [comment]
@bruth as per https://github.com/k3s-io/kine/pull/275#issuecomment-1976094545 it sounds like this does not resolve the error?

**Comment by bruth** [comment]
Checking it out again.

**Comment by bruth** [comment]
Found the root cause.. I had disabled an internal API that the KV bucket normally uses a while back since it was buggy at the time. However that had the side effect of having certain requests time out since directs gets were disabled. The error reporting simply appears as a timeout since there is not receiver of that direct get API.

I validated the timeout no longer occurs when creating the health check key-value pair which will prevent the issue noted in #274. This has been likely affecting all deployments of kine+NATS.

Also confirmed the CI passed this time.

**Comment by bruth** [comment]
I will update with an additional commit shortly to ensure that API is enabled for existing KV buckets.

**Comment by bruth** [comment]
@brandond Assuming CI passes, this is now ready to be reviewed and merged.

**Review by brandond — APPROVED** [review]

**Pull request merged**
