### PR TITLE
Bump nats.go to v1.27.1

### PR DESCRIPTION
**Pull request by dereknola**
The current commit `github.com/nats-io/nats.go v1.27.1-0.20230619112143-ec00e662324e` does not exist on the master branch, [that branch has been deleted](https://github.com/nats-io/nats.go/commit/ec00e662324e). We will now match to the actual v1.27.1 tagged release.

### CODE REVIEW

**Review by cwayne18 — APPROVED** [review]

**Review by briandowns — APPROVED** [review]

**Comment by brandond** [comment]
@bruth any concerns about this?

**Review by brandond — CHANGES_REQUESTED** [review]
Want confirmation from the Synadia folks that this won't interfere with
* https://github.com/k3s-io/kine/pull/194

**Comment by dereknola** [comment]
@bruth ?

**Review by brandond — APPROVED** [review]

**Comment by bruth** [comment]
All good. I will fix up #194

**Pull request merged**
